### PR TITLE
bn254G1Sum added with caveats of return.

### PR DESCRIPTION
**Pull request by anupsv**
bn254G1Sum function added. Final call translation needs some more information.

### CODE REVIEW

**Comment by jonathanpwang** [comment]
The intention was that every struct that had `JsCircuitValue256` would have a corresponding typescript struct of the same format where `JsCircuitValue256` is replaced by `CircuitValue256`, because `CircuitValue256` is what you usually get access to in the REPL. Unfortunately for now it probably does just require some manual conversion in `halo2-lib-js`.

**Comment by anupsv** [comment]
> The intention was that every struct that had `JsCircuitValue256` would have a corresponding typescript struct of the same format where `JsCircuitValue256` is replaced by `CircuitValue256`, because `CircuitValue256` is what you usually get access to in the REPL. Unfortunately for now it probably does just require some manual conversion in `halo2-lib-js`.

I see. I add some new changes to it. Essentially it does a `to_circuit_values_256` call to get `JsCircuitBn254G1Affine` and  I add it to the cell like so:
`
this.Cell(this._halo2lib.constant(jsBn254G1AffinePoint.x.toString()));
this.Cell(this._halo2lib.constant(jsBn254G1AffinePoint.y.toString()));
`

Definitely not ideal but if it could get the function working for the demo, that'd be great.

**Review by jonathanpwang — APPROVED** [review]
LGTM, will merge first and then refactor a bit

**Comment by jonathanpwang** [comment]
> > The intention was that every struct that had `JsCircuitValue256` would have a corresponding typescript struct of the same format where `JsCircuitValue256` is replaced by `CircuitValue256`, because `CircuitValue256` is what you usually get access to in the REPL. Unfortunately for now it probably does just require some manual conversion in `halo2-lib-js`.
> 
> I see. I add some new changes to it. Essentially it does a `to_circuit_values_256` call to get `JsCircuitBn254G1Affine` and I add it to the cell like so: `this.Cell(this._halo2lib.constant(jsBn254G1AffinePoint.x.toString())); this.Cell(this._halo2lib.constant(jsBn254G1AffinePoint.y.toString()));`
> 
> Definitely not ideal but if it could get the function working for the demo, that'd be great.

Probably needs to be `witness`, not `constant`, but I'll refactor.

**Pull request merged**
